In [2]:
import requests

In [11]:
base_url = 'https://npiregistry.cms.hhs.gov/api/'

In [499]:
def fetch_npi_data(npi):
    # Construct the URL for the API request
    #url = base_url + 'version=2.1'
    params = {
        'number': npi,
        'version': '2.1'
    }
    
    url = 'https://npiregistry.cms.hhs.gov/api/?version=2.1'
    try:
        # Send the API request
        response = requests.get(url, params=params)

        # Check if the request was successful (status code 200)
        if response.status_code == 200:
            data = response.json()
            # Process the data as per your requirements
            return data
        else:
            # Request was not successful, handle the error
            print('Error:', response.status_code)
            return None
    except requests.exceptions.RequestException as e:
        # Request encountered an exception, handle the error
        print('Error:', str(e))
        return None

In [110]:
npi_number = '1629395249'  # Replace with the desired NPI number
result = fetch_npi_data(npi_number)

if result:
    # Process the result as needed
    print(result)
else:
    print('Failed to fetch NPI data.')

{'result_count': 1, 'results': [{'created_epoch': '1271881919000', 'enumeration_type': 'NPI-1', 'last_updated_epoch': '1604936407000', 'number': '1629395249', 'addresses': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': '1630 S CONGRESS AVE STE 200', 'city': 'PALM SPRINGS', 'state': 'FL', 'postal_code': '334612171', 'telephone_number': '561-253-3980', 'fax_number': '561-253-3985'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1630 S CONGRESS AVE', 'city': 'PALM SPRINGS', 'state': 'FL', 'postal_code': '334612171', 'telephone_number': '561-253-3980', 'fax_number': '561-253-3985'}], 'practiceLocations': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1204 N VERCLER RD STE 101', 'city': 'SPOKANE VALLEY', 'state': 'WA', 'postal_code': '992161020', 'telephone_number': '509-228-1000', 'fax_number': '509-252-9300'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1204 N VERCLER RD STE 201', 'city': 'SPOKANE VALLEY', 'state': 'WA', 'postal_code': '992161020', 'telephone_number': '509-228-1000', 'fax_number': '509-252-9300'}], 'basic': {'first_name': 'VIJAY', 'last_name': 'NARENDRAN', 'middle_name': 'KUMAR', 'credential': 'M.D., MBA', 'sole_proprietor': 'NO', 'gender': 'M', 'enumeration_date': '2010-04-21', 'last_updated': '2020-11-09', 'certification_date': '2020-11-09', 'status': 'A'}, 'taxonomies': [{'code': '207RH0003X', 'taxonomy_group': '', 'desc': 'Internal Medicine, Hematology & Oncology', 'state': 'NY', 'license': '272229', 'primary': True}], 'identifiers': [], 'endpoints': [], 'other_names': []}]}

In [20]:
import pandas as pd

In [21]:
result

{'result_count': 1,
 'results': [{'created_epoch': '1271881919000',
   'enumeration_type': 'NPI-1',
   'last_updated_epoch': '1604936407000',
   'number': '1629395249',
   'addresses': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'MAILING',
     'address_type': 'DOM',
     'address_1': '1630 S CONGRESS AVE STE 200',
     'city': 'PALM SPRINGS',
     'state': 'FL',
     'postal_code': '334612171',
     'telephone_number': '561-253-3980',
     'fax_number': '561-253-3985'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '1630 S CONGRESS AVE',
     'city': 'PALM SPRINGS',
     'state': 'FL',
     'postal_code': '334612171',
     'telephone_number': '561-253-3980',
     'fax_number': '561-253-3985'}],
   'practiceLocations': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '1204 N VERCLER RD STE 101',
     'city': 'SPOKANE VALLEY',
     'state': 'WA',
     'postal_code': '992161020',
     'telephone_number': '509-228-1000',
     'fax_number': '509-252-9300'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '1204 N VERCLER RD STE 201',
     'city': 'SPOKANE VALLEY',
     'state': 'WA',
     'postal_code': '992161020',
     'telephone_number': '509-228-1000',
     'fax_number': '509-252-9300'}],
   'basic': {'first_name': 'VIJAY',
    'last_name': 'NARENDRAN',
    'middle_name': 'KUMAR',
    'credential': 'M.D., MBA',
    'sole_proprietor': 'NO',
    'gender': 'M',
    'enumeration_date': '2010-04-21',
    'last_updated': '2020-11-09',
    'certification_date': '2020-11-09',
    'status': 'A'},
   'taxonomies': [{'code': '207RH0003X',
     'taxonomy_group': '',
     'desc': 'Internal Medicine, Hematology & Oncology',
     'state': 'NY',
     'license': '272229',
     'primary': True}],
   'identifiers': [],
   'endpoints': [],
   'other_names': []}]}

In [27]:
for i in result['results']:
    print(i)

{'created_epoch': '1271881919000', 'enumeration_type': 'NPI-1', 'last_updated_epoch': '1604936407000', 'number': '1629395249', 'addresses': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': '1630 S CONGRESS AVE STE 200', 'city': 'PALM SPRINGS', 'state': 'FL', 'postal_code': '334612171', 'telephone_number': '561-253-3980', 'fax_number': '561-253-3985'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1630 S CONGRESS AVE', 'city': 'PALM SPRINGS', 'state': 'FL', 'postal_code': '334612171', 'telephone_number': '561-253-3980', 'fax_number': '561-253-3985'}], 'practiceLocations': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1204 N VERCLER RD STE 101', 'city': 'SPOKANE VALLEY', 'state': 'WA', 'postal_code': '992161020', 'telephone_number': '509-228-1000', 'fax_number': '509-252-9300'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1204 N VERCLER RD STE 201', 'city': 'SPOKANE VALLEY', 'state': 'WA', 'postal_code': '992161020', 'telephone_number': '509-228-1000', 'fax_number': '509-252-9300'}], 'basic': {'first_name': 'VIJAY', 'last_name': 'NARENDRAN', 'middle_name': 'KUMAR', 'credential': 'M.D., MBA', 'sole_proprietor': 'NO', 'gender': 'M', 'enumeration_date': '2010-04-21', 'last_updated': '2020-11-09', 'certification_date': '2020-11-09', 'status': 'A'}, 'taxonomies': [{'code': '207RH0003X', 'taxonomy_group': '', 'desc': 'Internal Medicine, Hematology & Oncology', 'state': 'NY', 'license': '272229', 'primary': True}], 'identifiers': [], 'endpoints': [], 'other_names': []}

In [28]:
result['results']

[{'created_epoch': '1271881919000',
  'enumeration_type': 'NPI-1',
  'last_updated_epoch': '1604936407000',
  'number': '1629395249',
  'addresses': [{'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'MAILING',
    'address_type': 'DOM',
    'address_1': '1630 S CONGRESS AVE STE 200',
    'city': 'PALM SPRINGS',
    'state': 'FL',
    'postal_code': '334612171',
    'telephone_number': '561-253-3980',
    'fax_number': '561-253-3985'},
   {'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'LOCATION',
    'address_type': 'DOM',
    'address_1': '1630 S CONGRESS AVE',
    'city': 'PALM SPRINGS',
    'state': 'FL',
    'postal_code': '334612171',
    'telephone_number': '561-253-3980',
    'fax_number': '561-253-3985'}],
  'practiceLocations': [{'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'LOCATION',
    'address_type': 'DOM',
    'address_1': '1204 N VERCLER RD STE 101',
    'city': 'SPOKANE VALLEY',
    'state': 'WA',
    'postal_code': '992161020',
    'telephone_number': '509-228-1000',
    'fax_number': '509-252-9300'},
   {'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'LOCATION',
    'address_type': 'DOM',
    'address_1': '1204 N VERCLER RD STE 201',
    'city': 'SPOKANE VALLEY',
    'state': 'WA',
    'postal_code': '992161020',
    'telephone_number': '509-228-1000',
    'fax_number': '509-252-9300'}],
  'basic': {'first_name': 'VIJAY',
   'last_name': 'NARENDRAN',
   'middle_name': 'KUMAR',
   'credential': 'M.D., MBA',
   'sole_proprietor': 'NO',
   'gender': 'M',
   'enumeration_date': '2010-04-21',
   'last_updated': '2020-11-09',
   'certification_date': '2020-11-09',
   'status': 'A'},
  'taxonomies': [{'code': '207RH0003X',
    'taxonomy_group': '',
    'desc': 'Internal Medicine, Hematology & Oncology',
    'state': 'NY',
    'license': '272229',
    'primary': True}],
  'identifiers': [],
  'endpoints': [],
  'other_names': []}]

In [30]:
provider_data = result['results'][0]['basic']

In [32]:
provider_data

{'first_name': 'VIJAY',
 'last_name': 'NARENDRAN',
 'middle_name': 'KUMAR',
 'credential': 'M.D., MBA',
 'sole_proprietor': 'NO',
 'gender': 'M',
 'enumeration_date': '2010-04-21',
 'last_updated': '2020-11-09',
 'certification_date': '2020-11-09',
 'status': 'A'}

In [33]:
df = pd.DataFrame([provider_data])

In [34]:
df

,first_name,last_name,middle_name,credential,sole_proprietor,gender,enumeration_date,last_updated,certification_date,status
0,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A

In [76]:
result['results'][0]['practiceLocations']

[{'country_code': 'US',
  'country_name': 'United States',
  'address_purpose': 'LOCATION',
  'address_type': 'DOM',
  'address_1': '1204 N VERCLER RD STE 101',
  'city': 'SPOKANE VALLEY',
  'state': 'WA',
  'postal_code': '992161020',
  'telephone_number': '509-228-1000',
  'fax_number': '509-252-9300'},
 {'country_code': 'US',
  'country_name': 'United States',
  'address_purpose': 'LOCATION',
  'address_type': 'DOM',
  'address_1': '1204 N VERCLER RD STE 201',
  'city': 'SPOKANE VALLEY',
  'state': 'WA',
  'postal_code': '992161020',
  'telephone_number': '509-228-1000',
  'fax_number': '509-252-9300'}]

In [59]:
provider_data = result['results'][0]['basic']
address_data = result['results'][0]['addresses'][0]
practiceLocations = result['results'][0]['practiceLocations'][0]

# Combine basic details and address information
combined_data = {**provider_data, **address_data,**practiceLocations}

# Create a DataFrame from the combined data
df = pd.DataFrame([combined_data])

In [446]:
address.transpose('number')

ValueError: the 'axes' parameter is not supported in the pandas implementation of transpose()

In [61]:
combined_data

{'first_name': 'VIJAY',
 'last_name': 'NARENDRAN',
 'middle_name': 'KUMAR',
 'credential': 'M.D., MBA',
 'sole_proprietor': 'NO',
 'gender': 'M',
 'enumeration_date': '2010-04-21',
 'last_updated': '2020-11-09',
 'certification_date': '2020-11-09',
 'status': 'A',
 'country_code': 'US',
 'country_name': 'United States',
 'address_purpose': 'LOCATION',
 'address_type': 'DOM',
 'address_1': '1204 N VERCLER RD STE 101',
 'city': 'SPOKANE VALLEY',
 'state': 'WA',
 'postal_code': '992161020',
 'telephone_number': '509-228-1000',
 'fax_number': '509-252-9300'}

In [67]:
{**provider_data,**practiceLocations}

{'first_name': 'VIJAY',
 'last_name': 'NARENDRAN',
 'middle_name': 'KUMAR',
 'credential': 'M.D., MBA',
 'sole_proprietor': 'NO',
 'gender': 'M',
 'enumeration_date': '2010-04-21',
 'last_updated': '2020-11-09',
 'certification_date': '2020-11-09',
 'status': 'A',
 'country_code': 'US',
 'country_name': 'United States',
 'address_purpose': 'LOCATION',
 'address_type': 'DOM',
 'address_1': '1204 N VERCLER RD STE 101',
 'city': 'SPOKANE VALLEY',
 'state': 'WA',
 'postal_code': '992161020',
 'telephone_number': '509-228-1000',
 'fax_number': '509-252-9300'}

In [62]:
practiceLocations

{'country_code': 'US',
 'country_name': 'United States',
 'address_purpose': 'LOCATION',
 'address_type': 'DOM',
 'address_1': '1204 N VERCLER RD STE 101',
 'city': 'SPOKANE VALLEY',
 'state': 'WA',
 'postal_code': '992161020',
 'telephone_number': '509-228-1000',
 'fax_number': '509-252-9300'}

In [50]:
result['results'][0]['number']

'1629395249'

In [49]:
result['results'][0]['basic']

{'first_name': 'VIJAY',
 'last_name': 'NARENDRAN',
 'middle_name': 'KUMAR',
 'credential': 'M.D., MBA',
 'sole_proprietor': 'NO',
 'gender': 'M',
 'enumeration_date': '2010-04-21',
 'last_updated': '2020-11-09',
 'certification_date': '2020-11-09',
 'status': 'A'}

In [57]:
result['results'][0]['addresses'][1]

{'country_code': 'US',
 'country_name': 'United States',
 'address_purpose': 'LOCATION',
 'address_type': 'DOM',
 'address_1': '1630 S CONGRESS AVE',
 'city': 'PALM SPRINGS',
 'state': 'FL',
 'postal_code': '334612171',
 'telephone_number': '561-253-3980',
 'fax_number': '561-253-3985'}

In [58]:
result['results'][0]

{'created_epoch': '1271881919000',
 'enumeration_type': 'NPI-1',
 'last_updated_epoch': '1604936407000',
 'number': '1629395249',
 'addresses': [{'country_code': 'US',
   'country_name': 'United States',
   'address_purpose': 'MAILING',
   'address_type': 'DOM',
   'address_1': '1630 S CONGRESS AVE STE 200',
   'city': 'PALM SPRINGS',
   'state': 'FL',
   'postal_code': '334612171',
   'telephone_number': '561-253-3980',
   'fax_number': '561-253-3985'},
  {'country_code': 'US',
   'country_name': 'United States',
   'address_purpose': 'LOCATION',
   'address_type': 'DOM',
   'address_1': '1630 S CONGRESS AVE',
   'city': 'PALM SPRINGS',
   'state': 'FL',
   'postal_code': '334612171',
   'telephone_number': '561-253-3980',
   'fax_number': '561-253-3985'}],
 'practiceLocations': [{'country_code': 'US',
   'country_name': 'United States',
   'address_purpose': 'LOCATION',
   'address_type': 'DOM',
   'address_1': '1204 N VERCLER RD STE 101',
   'city': 'SPOKANE VALLEY',
   'state': 'WA',
   'postal_code': '992161020',
   'telephone_number': '509-228-1000',
   'fax_number': '509-252-9300'},
  {'country_code': 'US',
   'country_name': 'United States',
   'address_purpose': 'LOCATION',
   'address_type': 'DOM',
   'address_1': '1204 N VERCLER RD STE 201',
   'city': 'SPOKANE VALLEY',
   'state': 'WA',
   'postal_code': '992161020',
   'telephone_number': '509-228-1000',
   'fax_number': '509-252-9300'}],
 'basic': {'first_name': 'VIJAY',
  'last_name': 'NARENDRAN',
  'middle_name': 'KUMAR',
  'credential': 'M.D., MBA',
  'sole_proprietor': 'NO',
  'gender': 'M',
  'enumeration_date': '2010-04-21',
  'last_updated': '2020-11-09',
  'certification_date': '2020-11-09',
  'status': 'A'},
 'taxonomies': [{'code': '207RH0003X',
   'taxonomy_group': '',
   'desc': 'Internal Medicine, Hematology & Oncology',
   'state': 'NY',
   'license': '272229',
   'primary': True}],
 'identifiers': [],
 'endpoints': [],
 'other_names': []}

In [84]:
test_cases = pd.read_csv("C:/Users/GopinathPandit/OneDrive - ConcertAI/Desktop/test.csv", names= ['NPI'])

In [111]:
test_cases['NPI']

0    1043408578
1    1235233636
2    1659306249
3    1629395249
Name: NPI, dtype: int64

In [114]:
fetch_npi_data(1043408578)

{'result_count': 1,
 'results': [{'created_epoch': '1192025817000',
   'enumeration_type': 'NPI-1',
   'last_updated_epoch': '1594308770000',
   'number': '1043408578',
   'addresses': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
     'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER',
     'city': 'JOHNSON CITY',
     'state': 'TN',
     'postal_code': '37601',
     'telephone_number': '423-926-1171',
     'fax_number': '423-979-3609'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'MAILING',
     'address_type': 'DOM',
     'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
     'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER',
     'city': 'MOUNTAIN HOME',
     'state': 'TN',
     'postal_code': '37684',
     'telephone_number': '423-926-1171',
     'fax_number': '423-979-3609'}],
   'practiceLocations': [],
   'basic': {'first_name': 'MAILIEN',
    'last_name': 'ROGERS',
    'middle_name': 'REED',
    'credential': 'D.O.',
    'sole_proprietor': 'NO',
    'gender': 'F',
    'enumeration_date': '2007-10-10',
    'last_updated': '2020-07-09',
    'certification_date': '2020-07-09',
    'status': 'A',
    'name_prefix': 'Dr.'},
   'taxonomies': [{'code': '207RX0202X',
     'taxonomy_group': '',
     'desc': 'Internal Medicine, Medical Oncology',
     'state': 'TN',
     'license': '2083',
     'primary': True}],
   'identifiers': [{'code': '05',
     'desc': 'MEDICAID',
     'issuer': None,
     'identifier': 'Q055396',
     'state': 'TN'}],
   'endpoints': [{'endpointType': 'DIRECT',
     'endpointTypeDescription': 'Direct Messaging Address',
     'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com',
     'affiliation': 'N',
     'useDescription': '',
     'contentTypeDescription': '',
     'country_code': 'US',
     'country_name': 'United States',
     'address_type': 'DOM',
     'address_1': '111H Building 8 Dogwood Avenue',
     'address_2': 'James H Quillen VA Medical Center',
     'city': 'Johnson City',
     'state': 'TN',
     'postal_code': '37601'}],
   'other_names': []}]}

In [88]:
l = []

In [96]:
data = fetch_npi_data(1043408578)

In [89]:
for npi_number in test_cases['NPI']:
    l.append(npi_number)
    l.append(fetch_npi_data(npi_number))
    
print(l)

[{'result_count': 1, 'results': [{'created_epoch': '1192025817000', 'enumeration_type': 'NPI-1', 'last_updated_epoch': '1594308770000', 'number': '1043408578', 'addresses': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '111H BUILDING 8 DOGWOOD AVENUE', 'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER', 'city': 'JOHNSON CITY', 'state': 'TN', 'postal_code': '37601', 'telephone_number': '423-926-1171', 'fax_number': '423-979-3609'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': '111H BUILDING 8 DOGWOOD AVENUE', 'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER', 'city': 'MOUNTAIN HOME', 'state': 'TN', 'postal_code': '37684', 'telephone_number': '423-926-1171', 'fax_number': '423-979-3609'}], 'practiceLocations': [], 'basic': {'first_name': 'MAILIEN', 'last_name': 'ROGERS', 'middle_name': 'REED', 'credential': 'D.O.', 'sole_proprietor': 'NO', 'gender': 'F', 'enumeration_date': '2007-10-10', 'last_updated': '2020-07-09', 'certification_date': '2020-07-09', 'status': 'A', 'name_prefix': 'Dr.'}, 'taxonomies': [{'code': '207RX0202X', 'taxonomy_group': '', 'desc': 'Internal Medicine, Medical Oncology', 'state': 'TN', 'license': '2083', 'primary': True}], 'identifiers': [{'code': '05', 'desc': 'MEDICAID', 'issuer': None, 'identifier': 'Q055396', 'state': 'TN'}], 'endpoints': [{'endpointType': 'DIRECT', 'endpointTypeDescription': 'Direct Messaging Address', 'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com', 'affiliation': 'N', 'useDescription': '', 'contentTypeDescription': '', 'country_code': 'US', 'country_name': 'United States', 'address_type': 'DOM', 'address_1': '111H Building 8 Dogwood Avenue', 'address_2': 'James H Quillen VA Medical Center', 'city': 'Johnson City', 'state': 'TN', 'postal_code': '37601'}], 'other_names': []}]}, {'result_count': 1, 'results': [{'created_epoch': '1157683915000', 'enumeration_type': 'NPI-1', 'last_updated_epoch': '1183947785000', 'number': '1235233636', 'addresses': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': 'P.O. BOX 1559', 'city': 'STONY BROOK', 'state': 'NY', 'postal_code': '11790'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': 'UNIVERSITY HOSPITAL L5 SUITE 1', 'city': 'STONY BROOK', 'state': 'NY', 'postal_code': '11794', 'telephone_number': '631-444-2540'}], 'practiceLocations': [], 'basic': {'first_name': 'SHENHONG', 'last_name': 'WU', 'credential': 'M.D.', 'sole_proprietor': 'NO', 'gender': 'M', 'enumeration_date': '2006-09-07', 'last_updated': '2007-07-08', 'status': 'A', 'name_prefix': 'Dr.', 'name_suffix': '--'}, 'taxonomies': [{'code': '207RX0202X', 'taxonomy_group': '', 'desc': 'Internal Medicine, Medical Oncology', 'state': 'NY', 'license': '241559', 'primary': True}], 'identifiers': [], 'endpoints': [], 'other_names': []}]}, {'result_count': 1, 'results': [{'created_epoch': '1152672131000', 'enumeration_type': 'NPI-1', 'last_updated_epoch': '1588964652000', 'number': '1659306249', 'addresses': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': '5515 CLEVELAND AVE STE 1', 'city': 'STEVENSVILLE', 'state': 'MI', 'postal_code': '491279670', 'telephone_number': '269-429-6604', 'fax_number': '269-429-1715'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '5515 CLEVELAND AVE STE 1', 'city': 'STEVENSVILLE', 'state': 'MI', 'postal_code': '491279670', 'telephone_number': '269-429-6604', 'fax_number': '269-429-1715'}], 'practiceLocations': [], 'basic': {'first_name': 'THOMAS', 'last_name': 'SCHOMAKER', 'middle_name': 'D', 'credential': 'DO', 'sole_proprietor': 'NO', 'gender': 'M', 'enumeration_date': '2006-07-11', 'last_updated': '2020-05-08', 'certification_date': '2020-05-08', 'status': 'A'}, 'taxonomies': [{'code': '208000000X', 'taxonomy_group': '', 'desc': 'Pediatrics', 'state': 'MI', 'license': '5101012706', 'primary': True}], 'identifiers': [], 'endpoints': [], 'other_names': []}]}, {'result_count': 1, 'results': [{'created_epoch': '1271881919000', 'enumeration_type': 'NPI-1', 'last_updated_epoch': '1604936407000', 'number': '1629395249', 'addresses': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': '1630 S CONGRESS AVE STE 200', 'city': 'PALM SPRINGS', 'state': 'FL', 'postal_code': '334612171', 'telephone_number': '561-253-3980', 'fax_number': '561-253-3985'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1630 S CONGRESS AVE', 'city': 'PALM SPRINGS', 'state': 'FL', 'postal_code': '334612171', 'telephone_number': '561-253-3980', 'fax_number': '561-253-3985'}], 'practiceLocations': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1204 N VERCLER RD STE 101', 'city': 'SPOKANE VALLEY', 'state': 'WA', 'postal_code': '992161020', 'telephone_number': '509-228-1000', 'fax_number': '509-252-9300'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '1204 N VERCLER RD STE 201', 'city': 'SPOKANE VALLEY', 'state': 'WA', 'postal_code': '992161020', 'telephone_number': '509-228-1000', 'fax_number': '509-252-9300'}], 'basic': {'first_name': 'VIJAY', 'last_name': 'NARENDRAN', 'middle_name': 'KUMAR', 'credential': 'M.D., MBA', 'sole_proprietor': 'NO', 'gender': 'M', 'enumeration_date': '2010-04-21', 'last_updated': '2020-11-09', 'certification_date': '2020-11-09', 'status': 'A'}, 'taxonomies': [{'code': '207RH0003X', 'taxonomy_group': '', 'desc': 'Internal Medicine, Hematology & Oncology', 'state': 'NY', 'license': '272229', 'primary': True}], 'identifiers': [], 'endpoints': [], 'other_names': []}]}]

In [125]:
for i in data['results']:
    #print(type(i))
    print(i,end = '\n')

{'created_epoch': '1192025817000', 'enumeration_type': 'NPI-1', 'last_updated_epoch': '1594308770000', 'number': '1043408578', 'addresses': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '111H BUILDING 8 DOGWOOD AVENUE', 'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER', 'city': 'JOHNSON CITY', 'state': 'TN', 'postal_code': '37601', 'telephone_number': '423-926-1171', 'fax_number': '423-979-3609'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': '111H BUILDING 8 DOGWOOD AVENUE', 'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER', 'city': 'MOUNTAIN HOME', 'state': 'TN', 'postal_code': '37684', 'telephone_number': '423-926-1171', 'fax_number': '423-979-3609'}], 'practiceLocations': [], 'basic': {'first_name': 'MAILIEN', 'last_name': 'ROGERS', 'middle_name': 'REED', 'credential': 'D.O.', 'sole_proprietor': 'NO', 'gender': 'F', 'enumeration_date': '2007-10-10', 'last_updated': '2020-07-09', 'certification_date': '2020-07-09', 'status': 'A', 'name_prefix': 'Dr.'}, 'taxonomies': [{'code': '207RX0202X', 'taxonomy_group': '', 'desc': 'Internal Medicine, Medical Oncology', 'state': 'TN', 'license': '2083', 'primary': True}], 'identifiers': [{'code': '05', 'desc': 'MEDICAID', 'issuer': None, 'identifier': 'Q055396', 'state': 'TN'}], 'endpoints': [{'endpointType': 'DIRECT', 'endpointTypeDescription': 'Direct Messaging Address', 'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com', 'affiliation': 'N', 'useDescription': '', 'contentTypeDescription': '', 'country_code': 'US', 'country_name': 'United States', 'address_type': 'DOM', 'address_1': '111H Building 8 Dogwood Avenue', 'address_2': 'James H Quillen VA Medical Center', 'city': 'Johnson City', 'state': 'TN', 'postal_code': '37601'}], 'other_names': []}

In [133]:
for i,j in data['results'][0].items():
    print(i,j)

created_epoch 1192025817000
enumeration_type NPI-1
last_updated_epoch 1594308770000
number 1043408578
addresses [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '111H BUILDING 8 DOGWOOD AVENUE', 'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER', 'city': 'JOHNSON CITY', 'state': 'TN', 'postal_code': '37601', 'telephone_number': '423-926-1171', 'fax_number': '423-979-3609'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': '111H BUILDING 8 DOGWOOD AVENUE', 'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER', 'city': 'MOUNTAIN HOME', 'state': 'TN', 'postal_code': '37684', 'telephone_number': '423-926-1171', 'fax_number': '423-979-3609'}]
practiceLocations []
basic {'first_name': 'MAILIEN', 'last_name': 'ROGERS', 'middle_name': 'REED', 'credential': 'D.O.', 'sole_proprietor': 'NO', 'gender': 'F', 'enumeration_date': '2007-10-10', 'last_updated': '2020-07-09', 'certification_date': '2020-07-09', 'status': 'A', 'name_prefix': 'Dr.'}
taxonomies [{'code': '207RX0202X', 'taxonomy_group': '', 'desc': 'Internal Medicine, Medical Oncology', 'state': 'TN', 'license': '2083', 'primary': True}]
identifiers [{'code': '05', 'desc': 'MEDICAID', 'issuer': None, 'identifier': 'Q055396', 'state': 'TN'}]
endpoints [{'endpointType': 'DIRECT', 'endpointTypeDescription': 'Direct Messaging Address', 'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com', 'affiliation': 'N', 'useDescription': '', 'contentTypeDescription': '', 'country_code': 'US', 'country_name': 'United States', 'address_type': 'DOM', 'address_1': '111H Building 8 Dogwood Avenue', 'address_2': 'James H Quillen VA Medical Center', 'city': 'Johnson City', 'state': 'TN', 'postal_code': '37601'}]
other_names []

In [ ]:
def dict_parser(d):
    d2 = {}
    if type(d) == dict:
        for i in

In [99]:
df

   result_count                                            results
0             1  {'created_epoch': '1192025817000', 'enumeratio...

In [101]:
import pandas as pd
import json
from pandas.io.json import json_normalize


df = pd.json_normalize(data)
print(df)

   result_count                                            results
0             1  [{'created_epoch': '1192025817000', 'enumerati...

In [104]:
df

   result_count                                            results
0             1  [{'created_epoch': '1192025817000', 'enumerati...

In [103]:
pd.set_option('display.max_column', None)

In [105]:
df['results']

0    [{'created_epoch': '1192025817000', 'enumerati...
Name: results, dtype: object

In [109]:
for i in l[0]['results']:
    print(i)

{'created_epoch': '1192025817000', 'enumeration_type': 'NPI-1', 'last_updated_epoch': '1594308770000', 'number': '1043408578', 'addresses': [{'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'LOCATION', 'address_type': 'DOM', 'address_1': '111H BUILDING 8 DOGWOOD AVENUE', 'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER', 'city': 'JOHNSON CITY', 'state': 'TN', 'postal_code': '37601', 'telephone_number': '423-926-1171', 'fax_number': '423-979-3609'}, {'country_code': 'US', 'country_name': 'United States', 'address_purpose': 'MAILING', 'address_type': 'DOM', 'address_1': '111H BUILDING 8 DOGWOOD AVENUE', 'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER', 'city': 'MOUNTAIN HOME', 'state': 'TN', 'postal_code': '37684', 'telephone_number': '423-926-1171', 'fax_number': '423-979-3609'}], 'practiceLocations': [], 'basic': {'first_name': 'MAILIEN', 'last_name': 'ROGERS', 'middle_name': 'REED', 'credential': 'D.O.', 'sole_proprietor': 'NO', 'gender': 'F', 'enumeration_date': '2007-10-10', 'last_updated': '2020-07-09', 'certification_date': '2020-07-09', 'status': 'A', 'name_prefix': 'Dr.'}, 'taxonomies': [{'code': '207RX0202X', 'taxonomy_group': '', 'desc': 'Internal Medicine, Medical Oncology', 'state': 'TN', 'license': '2083', 'primary': True}], 'identifiers': [{'code': '05', 'desc': 'MEDICAID', 'issuer': None, 'identifier': 'Q055396', 'state': 'TN'}], 'endpoints': [{'endpointType': 'DIRECT', 'endpointTypeDescription': 'Direct Messaging Address', 'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com', 'affiliation': 'N', 'useDescription': '', 'contentTypeDescription': '', 'country_code': 'US', 'country_name': 'United States', 'address_type': 'DOM', 'address_1': '111H Building 8 Dogwood Avenue', 'address_2': 'James H Quillen VA Medical Center', 'city': 'Johnson City', 'state': 'TN', 'postal_code': '37601'}], 'other_names': []}

In [134]:
d = {'Name' : 'Gopi', 'l_name' : 'Pandit'}

In [135]:
d

{'Name': 'Gopi', 'l_name': 'Pandit'}

In [136]:
d.fromkeys()

TypeError: fromkeys expected at least 1 argument, got 0

In [137]:
l[0]['results']

[{'created_epoch': '1192025817000',
  'enumeration_type': 'NPI-1',
  'last_updated_epoch': '1594308770000',
  'number': '1043408578',
  'addresses': [{'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'LOCATION',
    'address_type': 'DOM',
    'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
    'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER',
    'city': 'JOHNSON CITY',
    'state': 'TN',
    'postal_code': '37601',
    'telephone_number': '423-926-1171',
    'fax_number': '423-979-3609'},
   {'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'MAILING',
    'address_type': 'DOM',
    'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
    'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER',
    'city': 'MOUNTAIN HOME',
    'state': 'TN',
    'postal_code': '37684',
    'telephone_number': '423-926-1171',
    'fax_number': '423-979-3609'}],
  'practiceLocations': [],
  'basic': {'first_name': 'MAILIEN',
   'last_name': 'ROGERS',
   'middle_name': 'REED',
   'credential': 'D.O.',
   'sole_proprietor': 'NO',
   'gender': 'F',
   'enumeration_date': '2007-10-10',
   'last_updated': '2020-07-09',
   'certification_date': '2020-07-09',
   'status': 'A',
   'name_prefix': 'Dr.'},
  'taxonomies': [{'code': '207RX0202X',
    'taxonomy_group': '',
    'desc': 'Internal Medicine, Medical Oncology',
    'state': 'TN',
    'license': '2083',
    'primary': True}],
  'identifiers': [{'code': '05',
    'desc': 'MEDICAID',
    'issuer': None,
    'identifier': 'Q055396',
    'state': 'TN'}],
  'endpoints': [{'endpointType': 'DIRECT',
    'endpointTypeDescription': 'Direct Messaging Address',
    'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com',
    'affiliation': 'N',
    'useDescription': '',
    'contentTypeDescription': '',
    'country_code': 'US',
    'country_name': 'United States',
    'address_type': 'DOM',
    'address_1': '111H Building 8 Dogwood Avenue',
    'address_2': 'James H Quillen VA Medical Center',
    'city': 'Johnson City',
    'state': 'TN',
    'postal_code': '37601'}],
  'other_names': []}]

In [208]:
pd.json_normalize(l[0]['results'])

,created_epoch,enumeration_type,last_updated_epoch,number,addresses,practiceLocations,taxonomies,identifiers,endpoints,other_names,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix
0,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.

In [167]:
pd.json_normalize(l[0]['results'][0])

,created_epoch,enumeration_type,last_updated_epoch,number,addresses,practiceLocations,taxonomies,identifiers,endpoints,other_names,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix
0,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.

In [179]:
fetch_npi_data(1043408578)['results']

[{'created_epoch': '1192025817000',
  'enumeration_type': 'NPI-1',
  'last_updated_epoch': '1594308770000',
  'number': '1043408578',
  'addresses': [{'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'LOCATION',
    'address_type': 'DOM',
    'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
    'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER',
    'city': 'JOHNSON CITY',
    'state': 'TN',
    'postal_code': '37601',
    'telephone_number': '423-926-1171',
    'fax_number': '423-979-3609'},
   {'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'MAILING',
    'address_type': 'DOM',
    'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
    'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER',
    'city': 'MOUNTAIN HOME',
    'state': 'TN',
    'postal_code': '37684',
    'telephone_number': '423-926-1171',
    'fax_number': '423-979-3609'}],
  'practiceLocations': [],
  'basic': {'first_name': 'MAILIEN',
   'last_name': 'ROGERS',
   'middle_name': 'REED',
   'credential': 'D.O.',
   'sole_proprietor': 'NO',
   'gender': 'F',
   'enumeration_date': '2007-10-10',
   'last_updated': '2020-07-09',
   'certification_date': '2020-07-09',
   'status': 'A',
   'name_prefix': 'Dr.'},
  'taxonomies': [{'code': '207RX0202X',
    'taxonomy_group': '',
    'desc': 'Internal Medicine, Medical Oncology',
    'state': 'TN',
    'license': '2083',
    'primary': True}],
  'identifiers': [{'code': '05',
    'desc': 'MEDICAID',
    'issuer': None,
    'identifier': 'Q055396',
    'state': 'TN'}],
  'endpoints': [{'endpointType': 'DIRECT',
    'endpointTypeDescription': 'Direct Messaging Address',
    'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com',
    'affiliation': 'N',
    'useDescription': '',
    'contentTypeDescription': '',
    'country_code': 'US',
    'country_name': 'United States',
    'address_type': 'DOM',
    'address_1': '111H Building 8 Dogwood Avenue',
    'address_2': 'James H Quillen VA Medical Center',
    'city': 'Johnson City',
    'state': 'TN',
    'postal_code': '37601'}],
  'other_names': []}]

In [180]:
pd.json_normalize(fetch_npi_data(1043408578)['results'],'addresses','enumeration_type')

,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number,enumeration_type
0,US,United States,LOCATION,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609,NPI-1
1,US,United States,MAILING,DOM,111H BUILDING 8 DOGWOOD AVENUE,PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER,MOUNTAIN HOME,TN,37684,423-926-1171,423-979-3609,NPI-1

In [190]:
data

{'result_count': 1,
 'results': [{'created_epoch': '1192025817000',
   'enumeration_type': 'NPI-1',
   'last_updated_epoch': '1594308770000',
   'number': '1043408578',
   'addresses': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
     'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER',
     'city': 'JOHNSON CITY',
     'state': 'TN',
     'postal_code': '37601',
     'telephone_number': '423-926-1171',
     'fax_number': '423-979-3609'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'MAILING',
     'address_type': 'DOM',
     'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
     'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER',
     'city': 'MOUNTAIN HOME',
     'state': 'TN',
     'postal_code': '37684',
     'telephone_number': '423-926-1171',
     'fax_number': '423-979-3609'}],
   'practiceLocations': [],
   'basic': {'first_name': 'MAILIEN',
    'last_name': 'ROGERS',
    'middle_name': 'REED',
    'credential': 'D.O.',
    'sole_proprietor': 'NO',
    'gender': 'F',
    'enumeration_date': '2007-10-10',
    'last_updated': '2020-07-09',
    'certification_date': '2020-07-09',
    'status': 'A',
    'name_prefix': 'Dr.'},
   'taxonomies': [{'code': '207RX0202X',
     'taxonomy_group': '',
     'desc': 'Internal Medicine, Medical Oncology',
     'state': 'TN',
     'license': '2083',
     'primary': True}],
   'identifiers': [{'code': '05',
     'desc': 'MEDICAID',
     'issuer': None,
     'identifier': 'Q055396',
     'state': 'TN'}],
   'endpoints': [{'endpointType': 'DIRECT',
     'endpointTypeDescription': 'Direct Messaging Address',
     'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com',
     'affiliation': 'N',
     'useDescription': '',
     'contentTypeDescription': '',
     'country_code': 'US',
     'country_name': 'United States',
     'address_type': 'DOM',
     'address_1': '111H Building 8 Dogwood Avenue',
     'address_2': 'James H Quillen VA Medical Center',
     'city': 'Johnson City',
     'state': 'TN',
     'postal_code': '37601'}],
   'other_names': []}]}

In [200]:
data['results'][0]['number']

'1043408578'

In [205]:
df2 = pd.json_normalize(data['results'][0]['basic'])

In [207]:
df2

,first_name,last_name,middle_name,credential,sole_proprietor,gender,enumeration_date,last_updated,certification_date,status,name_prefix
0,MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.

In [214]:
df3 = pd.json_normalize(l[0]['results'])

In [215]:
df3

,created_epoch,enumeration_type,last_updated_epoch,number,addresses,practiceLocations,taxonomies,identifiers,endpoints,other_names,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix
0,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.

In [230]:
df4 = pd.json_normalize(fetch_npi_data(1629395249)['results'],'addresses','number')

In [232]:
df4

,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number,number
0,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249
1,US,United States,LOCATION,DOM,1630 S CONGRESS AVE,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249

In [227]:
df5 = df3.merge(df4, on=['number'])

In [228]:
df5.columns

Index(['created_epoch', 'enumeration_type', 'last_updated_epoch', 'number',
       'addresses', 'practiceLocations', 'taxonomies', 'identifiers',
       'endpoints', 'other_names', 'basic.first_name', 'basic.last_name',
       'basic.middle_name', 'basic.credential', 'basic.sole_proprietor',
       'basic.gender', 'basic.enumeration_date', 'basic.last_updated',
       'basic.certification_date', 'basic.status', 'basic.name_prefix',
       'country_code', 'country_name', 'address_purpose', 'address_type',
       'address_1', 'address_2', 'city', 'state', 'postal_code',
       'telephone_number', 'fax_number'],
      dtype='object')

In [229]:
df5

,created_epoch,enumeration_type,last_updated_epoch,number,addresses,practiceLocations,taxonomies,identifiers,endpoints,other_names,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number
0,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,US,United States,LOCATION,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609
1,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,US,United States,MAILING,DOM,111H BUILDING 8 DOGWOOD AVENUE,PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER,MOUNTAIN HOME,TN,37684,423-926-1171,423-979-3609

In [235]:
p = fetch_npi_data(1629395249)['results']

In [236]:
p

[{'created_epoch': '1271881919000',
  'enumeration_type': 'NPI-1',
  'last_updated_epoch': '1604936407000',
  'number': '1629395249',
  'addresses': [{'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'MAILING',
    'address_type': 'DOM',
    'address_1': '1630 S CONGRESS AVE STE 200',
    'city': 'PALM SPRINGS',
    'state': 'FL',
    'postal_code': '334612171',
    'telephone_number': '561-253-3980',
    'fax_number': '561-253-3985'},
   {'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'LOCATION',
    'address_type': 'DOM',
    'address_1': '1630 S CONGRESS AVE',
    'city': 'PALM SPRINGS',
    'state': 'FL',
    'postal_code': '334612171',
    'telephone_number': '561-253-3980',
    'fax_number': '561-253-3985'}],
  'practiceLocations': [{'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'LOCATION',
    'address_type': 'DOM',
    'address_1': '1204 N VERCLER RD STE 101',
    'city': 'SPOKANE VALLEY',
    'state': 'WA',
    'postal_code': '992161020',
    'telephone_number': '509-228-1000',
    'fax_number': '509-252-9300'},
   {'country_code': 'US',
    'country_name': 'United States',
    'address_purpose': 'LOCATION',
    'address_type': 'DOM',
    'address_1': '1204 N VERCLER RD STE 201',
    'city': 'SPOKANE VALLEY',
    'state': 'WA',
    'postal_code': '992161020',
    'telephone_number': '509-228-1000',
    'fax_number': '509-252-9300'}],
  'basic': {'first_name': 'VIJAY',
   'last_name': 'NARENDRAN',
   'middle_name': 'KUMAR',
   'credential': 'M.D., MBA',
   'sole_proprietor': 'NO',
   'gender': 'M',
   'enumeration_date': '2010-04-21',
   'last_updated': '2020-11-09',
   'certification_date': '2020-11-09',
   'status': 'A'},
  'taxonomies': [{'code': '207RH0003X',
    'taxonomy_group': '',
    'desc': 'Internal Medicine, Hematology & Oncology',
    'state': 'NY',
    'license': '272229',
    'primary': True}],
  'identifiers': [],
  'endpoints': [],
  'other_names': []}]

In [238]:
pd.json_normalize(p,'addresses','number')

,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number,number
0,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249
1,US,United States,LOCATION,DOM,1630 S CONGRESS AVE,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249

In [239]:
pd.json_normalize(p,'practiceLocations','number')

,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number,number
0,US,United States,LOCATION,DOM,1204 N VERCLER RD STE 101,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300,1629395249
1,US,United States,LOCATION,DOM,1204 N VERCLER RD STE 201,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300,1629395249

In [501]:
# Defing a function to get the details..

import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize


raw_input = pd.read_csv("C:/Users/GopinathPandit/OneDrive - ConcertAI/Desktop/test.csv", names= ['NPI'])
raw_data = pd.DataFrame()
# df = pd.DataFrame()
# for i in raw_input['NPI']:
#     df = pd.json_normalize(fetch_npi_data(i)['results'])
#     raw_data = pd.concat([raw_data,df])

    
    
address = pd.DataFrame()
p_address = pd.DataFrame()
for i in raw_input['NPI']:
    df = pd.json_normalize(fetch_npi_data(i)['results'])
    df2 = pd.json_normalize(fetch_npi_data(i)['results'][0],'addresses','number')
    df3 = pd.json_normalize(fetch_npi_data(i)['results'][0],'practiceLocations','number')
    
    address = pd.concat([address,df2])
    p_address = pd.concat([p_address,df3])
    raw_data = pd.concat([raw_data,df])
    
    
    
# address = address.drop_duplicates(subset=['number','address_1'])
# p_address = p_address.drop_duplicates(subset=['number','address_1'])

required_col = ['number','enumeration_type',
 'basic.first_name',
 'basic.last_name',
 'basic.middle_name',
 'basic.credential',
 'basic.sole_proprietor',
 'basic.gender',
 'basic.enumeration_date',
 'basic.last_updated',
 'basic.certification_date',
 'basic.status',
 'basic.name_prefix',
 'basic.name_suffix']


basic_data = raw_data[required_col]


address['address_purpose'] = np.where(address['address_purpose'] == 'LOCATION', 'Primary Practice Address',address['address_purpose'])
p_address['address_purpose'] = 'Secondary Practice Address'

In [432]:
raw_data

,created_epoch,enumeration_type,last_updated_epoch,number,addresses,practiceLocations,taxonomies,identifiers,endpoints,other_names,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix,basic.name_suffix
0,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN
0,1157683915000,NPI-1,1183947785000,1235233636,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...",[],[],[],SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--
0,1152672131000,NPI-1,1588964652000,1659306249,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '208000000X', 'taxonomy_group': '', ...",[],[],[],THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN
0,1271881919000,NPI-1,1604936407000,1629395249,"[{'country_code': 'US', 'country_name': 'Unite...","[{'country_code': 'US', 'country_name': 'Unite...","[{'code': '207RH0003X', 'taxonomy_group': '', ...",[],[],[],VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN
0,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN
0,1157683915000,NPI-1,1183947785000,1235233636,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...",[],[],[],SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--
0,1152672131000,NPI-1,1588964652000,1659306249,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '208000000X', 'taxonomy_group': '', ...",[],[],[],THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN
0,1271881919000,NPI-1,1604936407000,1629395249,"[{'country_code': 'US', 'country_name': 'Unite...","[{'country_code': 'US', 'country_name': 'Unite...","[{'code': '207RH0003X', 'taxonomy_group': '', ...",[],[],[],VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN

In [433]:
p_address

,number,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number
0,1629395249,US,United States,Secondary Practice Address,DOM,1204 N VERCLER RD STE 101,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300
1,1629395249,US,United States,Secondary Practice Address,DOM,1204 N VERCLER RD STE 201,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300

In [434]:
address

,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number,number
0,US,United States,Primary Practice Address,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609,1043408578
1,US,United States,MAILING,DOM,111H BUILDING 8 DOGWOOD AVENUE,PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER,MOUNTAIN HOME,TN,37684,423-926-1171,423-979-3609,1043408578
0,US,United States,MAILING,DOM,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN,1235233636
1,US,United States,Primary Practice Address,DOM,UNIVERSITY HOSPITAL L5 SUITE 1,NaN,STONY BROOK,NY,11794,631-444-2540,NaN,1235233636
0,US,United States,MAILING,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715,1659306249
1,US,United States,Primary Practice Address,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715,1659306249
0,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249
1,US,United States,Primary Practice Address,DOM,1630 S CONGRESS AVE,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249

In [244]:
raw_data = pd.DataFrame()
for i in raw_input['NPI']:
    print(i)

1043408578
1235233636
1659306249
1629395249

In [252]:
raw_data = pd.DataFrame()

In [ ]:
raw_data.append

In [ ]:
pd.json_normalize(l[0]['results'])

In [422]:
raw_data = pd.DataFrame()
address = pd.DataFrame()
p_address = pd.DataFrame()
for i in raw_input['NPI']:
    df = pd.json_normalize(fetch_npi_data(i)['results'])
    df2 = pd.json_normalize(fetch_npi_data(i)['results'][0],'addresses','number')
    df3 = pd.json_normalize(fetch_npi_data(i)['results'][0],'practiceLocations','number')
    
    address = pd.concat([address,df2])
    p_address = pd.concat([p_address,df3])
    raw_data = pd.concat([raw_data,df])
    
    
    
# address = address.drop_duplicates(subset=['number','address_1'])
# p_address = p_address.drop_duplicates(subset=['number','address_1'])

required_col = ['number','enumeration_type',
 'basic.first_name',
 'basic.last_name',
 'basic.middle_name',
 'basic.credential',
 'basic.sole_proprietor',
 'basic.gender',
 'basic.enumeration_date',
 'basic.last_updated',
 'basic.certification_date',
 'basic.status',
 'basic.name_prefix',
 'basic.name_suffix']


basic_data = raw_data[required_col]


address['address_purpose'] = np.where(address['address_purpose'] == 'LOCATION', 'Primary Practice Address',address['address_purpose'])
p_address['address_purpose'] = 'Secondary Practice Address'

In [390]:
address[address['address_purpose'] == 'LOCATION']['address_purpose'].

C:\Users\GopinathPandit\AppData\Local\Temp\ipykernel_20616\1424534931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  address[address['address_purpose'] == 'LOCATION']['address_purpose'] = 'Primary Practice Address'

In [392]:
import numpy as np

In [419]:
address['address_purpose'] = np.where(address['address_purpose'] == 'LOCATION', 'Primary Practice Address',address['address_purpose'])
p_address['address_purpose'] = 'Secondary Practice Address'

In [420]:
p_address

,number,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number
0,1629395249,US,United States,Secondary Practice Address,DOM,1204 N VERCLER RD STE 101,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300
1,1629395249,US,United States,Secondary Practice Address,DOM,1204 N VERCLER RD STE 201,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300

In [423]:
address

,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number,number
0,US,United States,Primary Practice Address,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609,1043408578
1,US,United States,MAILING,DOM,111H BUILDING 8 DOGWOOD AVENUE,PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER,MOUNTAIN HOME,TN,37684,423-926-1171,423-979-3609,1043408578
0,US,United States,MAILING,DOM,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN,1235233636
1,US,United States,Primary Practice Address,DOM,UNIVERSITY HOSPITAL L5 SUITE 1,NaN,STONY BROOK,NY,11794,631-444-2540,NaN,1235233636
0,US,United States,MAILING,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715,1659306249
1,US,United States,Primary Practice Address,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715,1659306249
0,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249
1,US,United States,Primary Practice Address,DOM,1630 S CONGRESS AVE,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249

In [435]:
final_address = pd.concat([address,p_address])

In [443]:
df6 = basic_data.merge(final_address, on = ['number'])

In [426]:
df6.to_csv(path_or_buf = "C:/Users/GopinathPandit/OneDrive - ConcertAI/Desktop/address.csv", index= False)

In [444]:
df6

,number,enumeration_type,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix,basic.name_suffix,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number
0,1043408578,NPI-1,MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN,US,United States,Primary Practice Address,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609
1,1043408578,NPI-1,MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN,US,United States,MAILING,DOM,111H BUILDING 8 DOGWOOD AVENUE,PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER,MOUNTAIN HOME,TN,37684,423-926-1171,423-979-3609
2,1043408578,NPI-1,MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN,US,United States,Primary Practice Address,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609
3,1043408578,NPI-1,MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN,US,United States,MAILING,DOM,111H BUILDING 8 DOGWOOD AVENUE,PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER,MOUNTAIN HOME,TN,37684,423-926-1171,423-979-3609
4,1235233636,NPI-1,SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--,US,United States,MAILING,DOM,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN
5,1235233636,NPI-1,SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--,US,United States,Primary Practice Address,DOM,UNIVERSITY HOSPITAL L5 SUITE 1,NaN,STONY BROOK,NY,11794,631-444-2540,NaN
6,1235233636,NPI-1,SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--,US,United States,MAILING,DOM,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN
7,1235233636,NPI-1,SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--,US,United States,Primary Practice Address,DOM,UNIVERSITY HOSPITAL L5 SUITE 1,NaN,STONY BROOK,NY,11794,631-444-2540,NaN
8,1659306249,NPI-1,THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN,US,United States,MAILING,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715
9,1659306249,NPI-1,THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN,US,United States,Primary Practice Address,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715
10,1659306249,NPI-1,THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN,US,United States,MAILING,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715
11,1659306249,NPI-1,THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN,US,United States,Primary Practice Address,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715
12,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985
13,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,Primary Practice Address,DOM,1630 S CONGRESS AVE,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985
14,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,Secondary Practice Address,DOM,1204 N VERCLER RD STE 101,NaN,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300
15,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,Secondary Practice Address,DOM,1204 N VERCLER RD STE 201,NaN,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300
16,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985
17,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,Primary Practice Address,DOM,1630 S CONGRESS AVE,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985
18,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,Secondary Practice Address,DOM,1204 N VERCLER RD STE 101,NaN,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300
19,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,Secondary Practice Address,DOM,1204 N VERCLER RD STE 201,NaN,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300

In [410]:
basic_data.merge(address)

,number,enumeration_type,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix,basic.name_suffix,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number
0,1043408578,NPI-1,MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN,US,United States,Secondary Practice Address,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609
1,1043408578,NPI-1,MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN,US,United States,Secondary Practice Address,DOM,111H BUILDING 8 DOGWOOD AVENUE,PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER,MOUNTAIN HOME,TN,37684,423-926-1171,423-979-3609
2,1235233636,NPI-1,SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--,US,United States,Secondary Practice Address,DOM,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN
3,1235233636,NPI-1,SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--,US,United States,Secondary Practice Address,DOM,UNIVERSITY HOSPITAL L5 SUITE 1,NaN,STONY BROOK,NY,11794,631-444-2540,NaN
4,1659306249,NPI-1,THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN,US,United States,Secondary Practice Address,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715
5,1659306249,NPI-1,THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN,US,United States,Secondary Practice Address,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715
6,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,Secondary Practice Address,DOM,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985
7,1629395249,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN,US,United States,Secondary Practice Address,DOM,1630 S CONGRESS AVE,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985

In [361]:
p_address

,number,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number
0,1629395249,US,United States,LOCATION,DOM,1204 N VERCLER RD STE 101,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300

In [350]:
basic_data

,enumeration_type,first_name,last_name,middle_name,credential,sole_proprietor,gender,enumeration_date,last_updated,certification_date,status,name_prefix,name_suffix
0,NPI-1,MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN
0,NPI-1,SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--
0,NPI-1,THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN
0,NPI-1,VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN

In [346]:
d = [i.replace('basic.','') for i in basic_data.columns if 'basic' in i]

In [378]:
address.drop('address_purpose', axis = 1, inplace= True)
p_address.drop('address_purpose', axis = 1, inplace= True)

address['address_type'] = 'Primary Practice Address'
p_address['address_type'] = 'Secondary Practice Address'

In [365]:
address.columns

Index(['country_code', 'country_name', 'address_purpose', 'address_type',
       'address_1', 'address_2', 'city', 'state', 'postal_code',
       'telephone_number', 'fax_number', 'number'],
      dtype='object')

In [366]:
p_address.columns

Index(['number', 'country_code', 'country_name', 'address_purpose',
       'address_type', 'address_1', 'city', 'state', 'postal_code',
       'telephone_number', 'fax_number'],
      dtype='object')

In [372]:
df5 = pd.concat([address,p_address])

In [379]:
df5.drop_duplicates(subset= ['number','address_1'])

,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number,number
0,US,United States,LOCATION,Primary Practice Address,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609,1043408578
0,US,United States,MAILING,Primary Practice Address,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN,1235233636
1,US,United States,LOCATION,Primary Practice Address,UNIVERSITY HOSPITAL L5 SUITE 1,NaN,STONY BROOK,NY,11794,631-444-2540,NaN,1235233636
0,US,United States,MAILING,Primary Practice Address,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715,1659306249
0,US,United States,MAILING,Primary Practice Address,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249
1,US,United States,LOCATION,Primary Practice Address,1630 S CONGRESS AVE,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249
0,US,United States,LOCATION,Secondary Practice Address,1204 N VERCLER RD STE 101,NaN,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300,1629395249
1,US,United States,LOCATION,Secondary Practice Address,1204 N VERCLER RD STE 201,NaN,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300,1629395249

In [274]:
raw_data[['addresses','number']]

                                           addresses      number
0  [{'country_code': 'US', 'country_name': 'Unite...  1043408578
0  [{'country_code': 'US', 'country_name': 'Unite...  1235233636
0  [{'country_code': 'US', 'country_name': 'Unite...  1659306249
0  [{'country_code': 'US', 'country_name': 'Unite...  1629395249

In [276]:
pd.json_normalize(raw_data['addresses'][0])

,0,1
0,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
1,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
2,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
3,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."

In [280]:
df_json_normalized = pd.json_normalize(raw_data['addresses'].apply(lambda x: eval(x)))

0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
Name: addresses, dtype: object

In [287]:
raw_data['addresses']

0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
Name: addresses, dtype: object

In [447]:
address

,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number,number
0,US,United States,Primary Practice Address,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609,1043408578
1,US,United States,MAILING,DOM,111H BUILDING 8 DOGWOOD AVENUE,PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER,MOUNTAIN HOME,TN,37684,423-926-1171,423-979-3609,1043408578
0,US,United States,MAILING,DOM,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN,1235233636
1,US,United States,Primary Practice Address,DOM,UNIVERSITY HOSPITAL L5 SUITE 1,NaN,STONY BROOK,NY,11794,631-444-2540,NaN,1235233636
0,US,United States,MAILING,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715,1659306249
1,US,United States,Primary Practice Address,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715,1659306249
0,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249
1,US,United States,Primary Practice Address,DOM,1630 S CONGRESS AVE,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985,1629395249

In [448]:
address2  = address.groupby('number').agg(lambda x: list(x)).reset_index()

In [449]:
address2

,number,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number
0,1043408578,"[US, US]","[United States, United States]","[Primary Practice Address, MAILING]","[DOM, DOM]","[111H BUILDING 8 DOGWOOD AVENUE, 111H BUILDING...","[JAMES H QUILLEN VA MEDICAL CENTER, PO BOX 400...","[JOHNSON CITY, MOUNTAIN HOME]","[TN, TN]","[37601, 37684]","[423-926-1171, 423-926-1171]","[423-979-3609, 423-979-3609]"
1,1235233636,"[US, US]","[United States, United States]","[MAILING, Primary Practice Address]","[DOM, DOM]","[P.O. BOX 1559, UNIVERSITY HOSPITAL L5 SUITE 1]","[nan, nan]","[STONY BROOK, STONY BROOK]","[NY, NY]","[11790, 11794]","[nan, 631-444-2540]","[nan, nan]"
2,1629395249,"[US, US]","[United States, United States]","[MAILING, Primary Practice Address]","[DOM, DOM]","[1630 S CONGRESS AVE STE 200, 1630 S CONGRESS ...","[nan, nan]","[PALM SPRINGS, PALM SPRINGS]","[FL, FL]","[334612171, 334612171]","[561-253-3980, 561-253-3980]","[561-253-3985, 561-253-3985]"
3,1659306249,"[US, US]","[United States, United States]","[MAILING, Primary Practice Address]","[DOM, DOM]","[5515 CLEVELAND AVE STE 1, 5515 CLEVELAND AVE ...","[nan, nan]","[STEVENSVILLE, STEVENSVILLE]","[MI, MI]","[491279670, 491279670]","[269-429-6604, 269-429-6604]","[269-429-1715, 269-429-1715]"

In [456]:
df_expanded = pd.DataFrame(address2['address2'].to_list(), columns=[f'duplicate_value_{i+1}' for i in range(n)])

KeyError: 'duplicate_column'

In [458]:
address2.to_list()

AttributeError: 'DataFrame' object has no attribute 'to_list'

In [466]:
raw_data['addresses'][0]

0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
0    [{'country_code': 'US', 'country_name': 'Unite...
Name: addresses, dtype: object

In [472]:
test = pd.json_normalize(raw_data['addresses'])

In [473]:
test.columns =  ['Mailing', 'Primary']

In [474]:
test

,Mailing,Primary
0,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
1,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
2,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
3,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
4,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
5,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
6,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."
7,"{'country_code': 'US', 'country_name': 'United...","{'country_code': 'US', 'country_name': 'United..."

In [475]:
pd.json_normalize(test['Mailing'])

,country_code,country_name,address_purpose,address_type,address_1,address_2,city,state,postal_code,telephone_number,fax_number
0,US,United States,LOCATION,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609
1,US,United States,MAILING,DOM,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN
2,US,United States,MAILING,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715
3,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985
4,US,United States,LOCATION,DOM,111H BUILDING 8 DOGWOOD AVENUE,JAMES H QUILLEN VA MEDICAL CENTER,JOHNSON CITY,TN,37601,423-926-1171,423-979-3609
5,US,United States,MAILING,DOM,P.O. BOX 1559,NaN,STONY BROOK,NY,11790,NaN,NaN
6,US,United States,MAILING,DOM,5515 CLEVELAND AVE STE 1,NaN,STEVENSVILLE,MI,491279670,269-429-6604,269-429-1715
7,US,United States,MAILING,DOM,1630 S CONGRESS AVE STE 200,NaN,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985

In [477]:
raw_data.to_csv(path_or_buf = "C:/Users/GopinathPandit/OneDrive - ConcertAI/Desktop/raw.csv", index= False)

In [478]:
raw_input

          NPI
0  1043408578
1  1235233636
2  1659306249
3  1629395249

In [492]:
l = []
for i in raw_input['NPI']:
    l.append(fetch_npi_data(i)['results'])

In [493]:
l

[[{'created_epoch': '1192025817000',
   'enumeration_type': 'NPI-1',
   'last_updated_epoch': '1594308770000',
   'number': '1043408578',
   'addresses': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
     'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER',
     'city': 'JOHNSON CITY',
     'state': 'TN',
     'postal_code': '37601',
     'telephone_number': '423-926-1171',
     'fax_number': '423-979-3609'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'MAILING',
     'address_type': 'DOM',
     'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
     'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER',
     'city': 'MOUNTAIN HOME',
     'state': 'TN',
     'postal_code': '37684',
     'telephone_number': '423-926-1171',
     'fax_number': '423-979-3609'}],
   'practiceLocations': [],
   'basic': {'first_name': 'MAILIEN',
    'last_name': 'ROGERS',
    'middle_name': 'REED',
    'credential': 'D.O.',
    'sole_proprietor': 'NO',
    'gender': 'F',
    'enumeration_date': '2007-10-10',
    'last_updated': '2020-07-09',
    'certification_date': '2020-07-09',
    'status': 'A',
    'name_prefix': 'Dr.'},
   'taxonomies': [{'code': '207RX0202X',
     'taxonomy_group': '',
     'desc': 'Internal Medicine, Medical Oncology',
     'state': 'TN',
     'license': '2083',
     'primary': True}],
   'identifiers': [{'code': '05',
     'desc': 'MEDICAID',
     'issuer': None,
     'identifier': 'Q055396',
     'state': 'TN'}],
   'endpoints': [{'endpointType': 'DIRECT',
     'endpointTypeDescription': 'Direct Messaging Address',
     'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com',
     'affiliation': 'N',
     'useDescription': '',
     'contentTypeDescription': '',
     'country_code': 'US',
     'country_name': 'United States',
     'address_type': 'DOM',
     'address_1': '111H Building 8 Dogwood Avenue',
     'address_2': 'James H Quillen VA Medical Center',
     'city': 'Johnson City',
     'state': 'TN',
     'postal_code': '37601'}],
   'other_names': []}],
 [{'created_epoch': '1157683915000',
   'enumeration_type': 'NPI-1',
   'last_updated_epoch': '1183947785000',
   'number': '1235233636',
   'addresses': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'MAILING',
     'address_type': 'DOM',
     'address_1': 'P.O. BOX 1559',
     'city': 'STONY BROOK',
     'state': 'NY',
     'postal_code': '11790'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': 'UNIVERSITY HOSPITAL L5 SUITE 1',
     'city': 'STONY BROOK',
     'state': 'NY',
     'postal_code': '11794',
     'telephone_number': '631-444-2540'}],
   'practiceLocations': [],
   'basic': {'first_name': 'SHENHONG',
    'last_name': 'WU',
    'credential': 'M.D.',
    'sole_proprietor': 'NO',
    'gender': 'M',
    'enumeration_date': '2006-09-07',
    'last_updated': '2007-07-08',
    'status': 'A',
    'name_prefix': 'Dr.',
    'name_suffix': '--'},
   'taxonomies': [{'code': '207RX0202X',
     'taxonomy_group': '',
     'desc': 'Internal Medicine, Medical Oncology',
     'state': 'NY',
     'license': '241559',
     'primary': True}],
   'identifiers': [],
   'endpoints': [],
   'other_names': []}],
 [{'created_epoch': '1152672131000',
   'enumeration_type': 'NPI-1',
   'last_updated_epoch': '1588964652000',
   'number': '1659306249',
   'addresses': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'MAILING',
     'address_type': 'DOM',
     'address_1': '5515 CLEVELAND AVE STE 1',
     'city': 'STEVENSVILLE',
     'state': 'MI',
     'postal_code': '491279670',
     'telephone_number': '269-429-6604',
     'fax_number': '269-429-1715'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '5515 CLEVELAND AVE STE 1',
     'city': 'STEVENSVILLE',
     'state': 'MI',
     'postal_code': '491279670',
     'telephone_number': '269-429-6604',
     'fax_number': '269-429-1715'}],
   'practiceLocations': [],
   'basic': {'first_name': 'THOMAS',
    'last_name': 'SCHOMAKER',
    'middle_name': 'D',
    'credential': 'DO',
    'sole_proprietor': 'NO',
    'gender': 'M',
    'enumeration_date': '2006-07-11',
    'last_updated': '2020-05-08',
    'certification_date': '2020-05-08',
    'status': 'A'},
   'taxonomies': [{'code': '208000000X',
     'taxonomy_group': '',
     'desc': 'Pediatrics',
     'state': 'MI',
     'license': '5101012706',
     'primary': True}],
   'identifiers': [],
   'endpoints': [],
   'other_names': []}],
 [{'created_epoch': '1271881919000',
   'enumeration_type': 'NPI-1',
   'last_updated_epoch': '1604936407000',
   'number': '1629395249',
   'addresses': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'MAILING',
     'address_type': 'DOM',
     'address_1': '1630 S CONGRESS AVE STE 200',
     'city': 'PALM SPRINGS',
     'state': 'FL',
     'postal_code': '334612171',
     'telephone_number': '561-253-3980',
     'fax_number': '561-253-3985'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '1630 S CONGRESS AVE',
     'city': 'PALM SPRINGS',
     'state': 'FL',
     'postal_code': '334612171',
     'telephone_number': '561-253-3980',
     'fax_number': '561-253-3985'}],
   'practiceLocations': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '1204 N VERCLER RD STE 101',
     'city': 'SPOKANE VALLEY',
     'state': 'WA',
     'postal_code': '992161020',
     'telephone_number': '509-228-1000',
     'fax_number': '509-252-9300'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '1204 N VERCLER RD STE 201',
     'city': 'SPOKANE VALLEY',
     'state': 'WA',
     'postal_code': '992161020',
     'telephone_number': '509-228-1000',
     'fax_number': '509-252-9300'}],
   'basic': {'first_name': 'VIJAY',
    'last_name': 'NARENDRAN',
    'middle_name': 'KUMAR',
    'credential': 'M.D., MBA',
    'sole_proprietor': 'NO',
    'gender': 'M',
    'enumeration_date': '2010-04-21',
    'last_updated': '2020-11-09',
    'certification_date': '2020-11-09',
    'status': 'A'},
   'taxonomies': [{'code': '207RH0003X',
     'taxonomy_group': '',
     'desc': 'Internal Medicine, Hematology & Oncology',
     'state': 'NY',
     'license': '272229',
     'primary': True}],
   'identifiers': [],
   'endpoints': [],
   'other_names': []}]]

In [494]:
pd.DataFrame(l)

                                                   0
0  {'created_epoch': '1192025817000', 'enumeratio...
1  {'created_epoch': '1157683915000', 'enumeratio...
2  {'created_epoch': '1152672131000', 'enumeratio...
3  {'created_epoch': '1271881919000', 'enumeratio...

In [491]:
l[0]

{'result_count': 1,
 'results': [{'created_epoch': '1192025817000',
   'enumeration_type': 'NPI-1',
   'last_updated_epoch': '1594308770000',
   'number': '1043408578',
   'addresses': [{'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'LOCATION',
     'address_type': 'DOM',
     'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
     'address_2': 'JAMES H QUILLEN VA MEDICAL CENTER',
     'city': 'JOHNSON CITY',
     'state': 'TN',
     'postal_code': '37601',
     'telephone_number': '423-926-1171',
     'fax_number': '423-979-3609'},
    {'country_code': 'US',
     'country_name': 'United States',
     'address_purpose': 'MAILING',
     'address_type': 'DOM',
     'address_1': '111H BUILDING 8 DOGWOOD AVENUE',
     'address_2': 'PO BOX 4000 JAMES H QUILLEN VA MEDICAL CENTER',
     'city': 'MOUNTAIN HOME',
     'state': 'TN',
     'postal_code': '37684',
     'telephone_number': '423-926-1171',
     'fax_number': '423-979-3609'}],
   'practiceLocations': [],
   'basic': {'first_name': 'MAILIEN',
    'last_name': 'ROGERS',
    'middle_name': 'REED',
    'credential': 'D.O.',
    'sole_proprietor': 'NO',
    'gender': 'F',
    'enumeration_date': '2007-10-10',
    'last_updated': '2020-07-09',
    'certification_date': '2020-07-09',
    'status': 'A',
    'name_prefix': 'Dr.'},
   'taxonomies': [{'code': '207RX0202X',
     'taxonomy_group': '',
     'desc': 'Internal Medicine, Medical Oncology',
     'state': 'TN',
     'license': '2083',
     'primary': True}],
   'identifiers': [{'code': '05',
     'desc': 'MEDICAID',
     'issuer': None,
     'identifier': 'Q055396',
     'state': 'TN'}],
   'endpoints': [{'endpointType': 'DIRECT',
     'endpointTypeDescription': 'Direct Messaging Address',
     'endpoint': 'rogers.mailien@covenanthealth.cererdirect.com',
     'affiliation': 'N',
     'useDescription': '',
     'contentTypeDescription': '',
     'country_code': 'US',
     'country_name': 'United States',
     'address_type': 'DOM',
     'address_1': '111H Building 8 Dogwood Avenue',
     'address_2': 'James H Quillen VA Medical Center',
     'city': 'Johnson City',
     'state': 'TN',
     'postal_code': '37601'}],
   'other_names': []}]}

In [497]:
pd.json_normalize(pd.json_normalize(l)[0])

,created_epoch,enumeration_type,last_updated_epoch,number,addresses,practiceLocations,taxonomies,identifiers,endpoints,other_names,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix,basic.name_suffix
0,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN
1,1157683915000,NPI-1,1183947785000,1235233636,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...",[],[],[],SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--
2,1152672131000,NPI-1,1588964652000,1659306249,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '208000000X', 'taxonomy_group': '', ...",[],[],[],THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN
3,1271881919000,NPI-1,1604936407000,1629395249,"[{'country_code': 'US', 'country_name': 'Unite...","[{'country_code': 'US', 'country_name': 'Unite...","[{'code': '207RH0003X', 'taxonomy_group': '', ...",[],[],[],VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN

In [502]:
raw_data

,created_epoch,enumeration_type,last_updated_epoch,number,addresses,practiceLocations,taxonomies,identifiers,endpoints,other_names,basic.first_name,basic.last_name,basic.middle_name,basic.credential,basic.sole_proprietor,basic.gender,basic.enumeration_date,basic.last_updated,basic.certification_date,basic.status,basic.name_prefix,basic.name_suffix
0,1192025817000,NPI-1,1594308770000,1043408578,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...","[{'code': '05', 'desc': 'MEDICAID', 'issuer': ...","[{'endpointType': 'DIRECT', 'endpointTypeDescr...",[],MAILIEN,ROGERS,REED,D.O.,NO,F,2007-10-10,2020-07-09,2020-07-09,A,Dr.,NaN
0,1157683915000,NPI-1,1183947785000,1235233636,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '207RX0202X', 'taxonomy_group': '', ...",[],[],[],SHENHONG,WU,NaN,M.D.,NO,M,2006-09-07,2007-07-08,NaN,A,Dr.,--
0,1152672131000,NPI-1,1588964652000,1659306249,"[{'country_code': 'US', 'country_name': 'Unite...",[],"[{'code': '208000000X', 'taxonomy_group': '', ...",[],[],[],THOMAS,SCHOMAKER,D,DO,NO,M,2006-07-11,2020-05-08,2020-05-08,A,NaN,NaN
0,1271881919000,NPI-1,1604936407000,1629395249,"[{'country_code': 'US', 'country_name': 'Unite...","[{'country_code': 'US', 'country_name': 'Unite...","[{'code': '207RH0003X', 'taxonomy_group': '', ...",[],[],[],VIJAY,NARENDRAN,KUMAR,"M.D., MBA",NO,M,2010-04-21,2020-11-09,2020-11-09,A,NaN,NaN

In [514]:
pd.json_normalize(fetch_npi_data(i)['results'][0]['addresses'][1])

,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number
0,US,United States,LOCATION,DOM,1630 S CONGRESS AVE,PALM SPRINGS,FL,334612171,561-253-3980,561-253-3985

In [505]:
npi = fetch_npi_data(i)

In [516]:
pd.json_normalize(fetch_npi_data(i)['results'][0]['practiceLocations'][1])

,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number
0,US,United States,LOCATION,DOM,1204 N VERCLER RD STE 201,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300

In [518]:
pd.json_normalize(fetch_npi_data(i)['results'][0]['practiceLocations'][0])

,country_code,country_name,address_purpose,address_type,address_1,city,state,postal_code,telephone_number,fax_number
0,US,United States,LOCATION,DOM,1204 N VERCLER RD STE 101,SPOKANE VALLEY,WA,992161020,509-228-1000,509-252-9300

In [522]:
len(fetch_npi_data(i)['results'])

1

In [524]:
len(p)

1

In [529]:
len(p[0]['addresses'])

2